### PR TITLE
Update from `xdg` to `xdg-base-dirs`

### PR DESCRIPTION
**Pull request by philiptaron**
Per <https://github.com/srstevenson/xdg-base-dirs/tree/6.0.0#xdg-base-dirs>, the Python library formerly known as `xdg` is now `xdg-base-dirs`.

Updating the references causes a bump in minimum supported Python versions from 3.8 to 3.10. This seemed fine to me.

The `poetry.lock` file was updated using `poetry lock`.

### CODE REVIEW

**Comment by philiptaron** [comment]
I made this change in response to NixOS's version of frogmouth being broken. https://github.com/NixOS/nixpkgs/pull/263241

**Comment by davep** [comment]
As per https://github.com/Textualize/frogmouth/pull/59 - unless there's an actual benefit to this I'll keep the Python compatibility. Last I checked there was no difference in the library.

**Comment by philiptaron** [comment]
Yeah, there's no difference I can see in the actual library... and thus, no reason that the `xdg-base-dirs` developers ought to raise its minimum Python version to 3.8. 🤕 This entire pain is due to that decision.

**Comment by davep** [comment]
Yup, there's no obvious benefit in them having raised the minimum Python version. It's an unfortunate decision.

**Pull request closed without merging**
